In [5]:
# 1.Write a Python code to calculate the multiplication and sum of two numbers.

a = int(input())
b = int(input())

print("The Multiplication of two numbers is:-", a*b)
print("The Sum of two numbers is:-", a+b)



 10
 20


The Multiplication of two numbers is:- 200
The Sum of two numbers is:- 30


In [11]:
# 2.Write a Python code to print the Sum of a current number and a previous number 
# as per given range of numbers.

a = int(input())

if a == 0:
    print("The sum is:-", 0)
else:
    sum = 0; pn = 0
    for i in range(1, a+1):
        sum = pn + i
        print("Current number", i, "Previous number",pn,"sum:-", sum)
        pn = i
    

 5


Current number 1 Previous number 0 sum:- 1
Current number 2 Previous number 1 sum:- 3
Current number 3 Previous number 2 sum:- 5
Current number 4 Previous number 3 sum:- 7
Current number 5 Previous number 4 sum:- 9


In [12]:
# 3.Write a Python code to print characters present at an even index number.

a = input()
print("Characters present at an even index number is:-")
for i in range(0,len(a)):
    if i%2 == 0:
        print(a[i])


 Hello DCS


Characters present at an even index number is:-
H
l
o
D
S


In [1]:
# 4.Write a Python code to remove first n characters from a string.
a = input()
n = int(input())
print(f"The String after removing the first {n} char is:-",a.replace(a[:n], ''))



 dhruvi
 4


The String after removing the first 4 char is:- vi


In [70]:
# 5.Write a Python code to check if the first and 
# last numbers of a list are the same.

l1 = [int(x) for x in input().split()]

print(l1)
print("Are the first and last number of list same???")
if l1[0] == l1[-1]:
    print("YES")
else:
    print("NO")

 10 11 10


[10, 11, 10]
Are the first and last number of list same???
YES


In [14]:
# 6.Write a Python code to display numbers from a list divisible by 5.

l1 = [int(i) for i in input("Enter number--->").split(",")]
print(l1)
count = 0

for i in l1:
    if i % 5 == 0:
        print(i)
        count += 1
        continue
if count == 0:
    print("There is no any number which is divisible by 5")

Enter number---> 5,2,15


[5, 2, 15]
5
15


In [5]:
#7.Write a Python code to find how often the 
# substring appears in the given string.

a = "I am Dhruvi. My name is DHRUVI. Hello, Dhruvi"
b = "Dhruvi"

print("Original String is:-",a)
print("Substring is:-",b)

print(f"The total number of appeared Substring is {a.count(b)}")

Original String is:- I am Dhruvi. My name is DHRUVI. Hello, Dhruvi
Substring is:- Dhruvi
The total number of appeared Substring is 2


In [76]:
# 8.Write a Python code to print multiplication Table of a given number.

a = int(input())

for i in range(1, 11):
    print(f"{a} * {i} = {a*i}")

 5


5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [4]:
# 9.	Write a Python code to print the following pattern.
# 1
# 2 2
# 3 3 3
# ………

a = int(input("enter number: "))

for i in range(1,a+1):
    for j in range(0,i):
        print(i, end=" ")
    print()

enter number:  5


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [5]:
# 10.Write a Python code to check if the given number is palindrome or not.

a = input()
if a[::] == a[::-1]:
    print("the given number is palindrom")
else:
    print("the given number is not palindrome")

 1221


the given number is palindrom


In [1]:
# 11.Given two lists of numbers, write a Python code to create a new list such
#that the latest list should contain odd numbers from the first list and
#even numbers from the second list.
l1 = [int(i) for i in input("Enter elements: ").split()]
l2 = [int(i) for i in input("Enter elements: ").split()]
l3 = [i for i in l1 if i%2 != 0] + [i for i in l2 if i%2 == 0]
print(l3)

Enter elements:  2 3 4 5 6
Enter elements:  1 8 3 5 4


[3, 5, 8, 4]


In [2]:
# 12. Write a Python code to get each digit from a number in the reverse order.

num = input("Enter Number-->")
num1 = int(num[::-1])
print(num1, type(num1))

Enter Number--> 234


432 <class 'int'>


In [2]:
''' 13. Write a Python code to calculate income tax for the given income by adhering to the rules below.
Taxable Income	Rate (in %)
First $10,000	0
Next $10,000	10
The remaining	20
Expected Output:
For example, suppose the income is 45000, and the income tax payable is
10000*0% + 10000*10%  + 25000*20% = $6000.
'''
income = int(input("enter the income: "))
tax_payable = 0
print("Given income", income)

if income <= 10000:
    tax_payable = 0
elif income <= 20000:
    # no tax on first 10,000
    x = income - 10000
    # 10% tax
    tax_payable = x * 10 / 100
else:
    # first 10,000
    tax_payable = 0

    # next 10,000 10% tax
    tax_payable = 10000 * 10 / 100

    # remaining 20%tax
    tax_payable += (income - 20000) * 20 / 100

print("Total tax to pay is", tax_payable)


enter the income:  45000


Given income 45000
Total tax to pay is 6000.0


In [27]:
# 14. Write a Python code to find sum of digits of a given number.

a = input("Enter the Number--->")
sum = 0
for i in a:  
    sum = sum + int(i)
  
print("The sum of digits of a given number is--->",sum)


# EXTRA

# a = input("Enter the Number--->")
# b = list(int(i) for i in a)
# sum = 0

# for i in b:
#    sum = sum + i

# print("The sum of digits of a given number is--->",sum)

Enter the Number---> 25


The sum of digits of a given number is---> 7


In [ ]:
#15.Write a Python code to print Fibonacci series. [ 1 1 2 3 5 8…….]
n= int(input("enter the number: "))

num1= 0
num2= 1

#print("fibonnaci series:",num1,num2,end=" ")
# Check if input is 0 then it will
# print incorrect input
for i in range(0, n):
    if n < 0:
        print("Incorrect input")

# Check if n is 0
# then it will return 0
    elif n == 0:
        print(0) 

# Check if n is 1,2
# it will return 1
    elif n == 1 or n == 2:
        print (1, end=" ")

    else:
        print(num1, end=" ")
        num1, num2 = num2, num1 + num2

enter the number:  8


0 1 1 2 3 5 8 13 

In [3]:
n= int(input("enter the number: "))

a= 0
b= 1

#print("fibonnaci series:",num1,num2,end=" ")
# Check if input is 0 then it will
# print incorrect input
for i in range(0, n):     
    print(a, end=" ")    
    a, b = b, a+b


enter the number:  8


0 1 1 2 3 5 8 13 

In [21]:
# 16.Write a Python code to calculate sum of all numbers 
# from 1 to a given number.

n = int(input("enter the number: "))
sum = 0
for i in range(1,n+1):
    sum += i
    
print("sum of all given number upto",n,"is",sum)

enter the number:  5


sum of all given number upto 5 is 15


In [2]:
# 17.Write a Python code to count the total number of digits 
# in a number.

# n = input("enter the number: ")
# print(len(n))

num=int(input("enter the number"))
count=0
while num>0:
   num=num//10
   count=count+1 
print(count)

# EXTRA
# n = input("enter the number: ")
# n1 = []
# for j in n:
#    if (n.count(j)>=1 and j not in n1):
#        print(f"the total number of {j} in {n} is",n.count(j))
#        n1.append(j)

enter the number 154


3


In [4]:
# 18.Write a Python code to print all prime numbers within a range.
start = int(input("enter starting range: "))
end = int(input("enter ending range: "))

print("prime number is:")
for i in range(start,end+1):
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i, end = " ")

# start = int(input("enter starting range: "))
# end = int(input("enter ending range: "))
# for number in range(start, end+1):  # Start checking from 2 and go up to an arbitrary upper limit
#     if number <= 1:
#         continue
#     if number <= 3:
#         print(number)

#     if number % 2 == 0 or number % 3 == 0:
#         continue
#     i = 5
#     while i * i <= number:
#         if number % i == 0 or number % (i + 2) == 0:
#             break
#         i += 6
#     else:  # This else block is executed when the while loop completes without a break
#         print(number)



enter starting range:  1
enter ending range:  10


prime number is:
2 3 5 7 

In [19]:
#19.Write a Python code to find the factorial of a given number.

def fact(num):
    if num == 1 or num == 0:
        return 1
    else:
        return (num*fact(num-1))
n = int(input("Enter the number-->"))       
print(f"The factorial of {n} is",fact(n))

Enter the number--> 3


The factorial of 3 is 6


In [78]:
# 19
n =5
fact = 1
if n == 1:
    print ("Factorial is 1")
for i in range(1,n+1):
    fact = fact*i
print(fact)

120


In [21]:
#20.Write a Python code to print list in reverse order 
# using a loop.

l = [int(i) for i in input("Enter the number-->").split()]
print("The original list is {}".format(l))
print("The reversal list is", l[::-1])

Enter the number--> 1 2 3


The original list is [1, 2, 3]
The reversal list is [3, 2, 1]


In [8]:
#21.Write a Python code to print elements from 
# a given list present at odd index positions.

l = [int(i) for i in input("Enter the number-->").split()]

for i in range(len(l)):
    if i%2 != 0:
        print(l[i])

Enter the number--> 1 2 3 4 5 6


2
4
6


In [30]:
# 22.	Write a function to find area of a circle.
import math
def area(r):
    a = r*r*math.pi
    return a
    
print("The area of the given radius is",area(int(input("Enter the radius-->"))))

Enter the radius--> 6


The area of the given radius is 113.09733552923255


In [33]:
# 23.	Write a function to find volume of a cylinder.
import math

def volume(r,h):
    v = r*r*h*math.pi
    return v
print("The volume of cylinder is",volume(int(input("Enter the radius-->")),int(input("Enter the height-->"))))    

Enter the radius--> 5
Enter the height--> 6


The volume of cylinder is 471.23889803846896


In [ ]:
# 24.Write a function to check given number is odd or even.

def odd_even(num):
    if num % 2 == 0:
        return f'the number {num} is even.'
    else:
        return f'the number {num} is odd.'

print(odd_even(int(input("Enter the Number--->"))))

Enter the Number---> 4


the number 4 is even.


In [15]:
#25.Write a function to find maximum number from the given three numbers
# Demonstrate the concept of default argument.

def maximum(a=0, b=0, c=30):
    return max(a, b, c)

print("The maximum number is:",maximum(int(input("Enter the Number--->")), int(input("Enter the Number--->")), int(input("Enter the Number--->"))))

Enter the Number---> 45
Enter the Number---> 42
Enter the Number---> 25


The maximum number is: 45


In [8]:
#26.Write a function that calculates the perimeter of a rectangle given its length and width.
# Demonstrate the concept of keyword largument.

def perimeter_rectangle(length, width):
    return 2*(length + width)
    

print("perimeter of retangle is: ",perimeter_rectangle(length = int(input("Enter Length --->")), width = int(input("Enter Width--->"))))


# def perimeter_rectangle(**kwargs):
#     return 2*(kwargs['length'] + kwargs['width'])

# print("perimeter of retangle is: ",perimeter_rectangle(length = 5, width = 10))


Enter Length ---> 15
Enter Width---> 10


perimeter of retangle is:  50


In [11]:
#27.Write a function that counts the number of vowels 
# (a, e, i, o, u) in a given string.

def count_vowels(str):
    count = 0
    vowels = 'aeiouAEIOU'
    
    for i in str:
        if i in vowels:
            count += 1
    return count
print("number of vowels:",count_vowels(input("Enter the String-->")))


#def count_vowels(str):
#    a = str.count('a')
#    e = str.count('e')
#    i = str.count('i')
#    o = str.count('o')
#    u = str.count('u')
#    return (a+e+i+o+u)

# print("number of vowels:",count_vowels(input("Enter the String-->")))

Enter the String--> hello dsc


number of vowels: 2


In [14]:
#28.Write a function that takes a list of numbers 
# and returns thesum of all the numbers.

def sum_list(lst):
    return sum(lst)
    
print("The sum of all elements of list:",sum_list(int(i) for i in input("Enter elements:").split()))

Enter elements: 1 2 3 4 5 6


The sum of all elements of list: 21


In [21]:
#29.Write a function that takes a string 
# and returns the reversed string.

def reverse_str(str):
    return str[::-1]

print("The reversed string: ",reverse_str(input("Enter the String-->")))

Enter the String--> Hello DCS


The reversed string:  SCD olleH


In [25]:
#30.Write a function that checks whether a given number is prime or not.

def check_prime(num):
    for i in range(2,num):
        if num % i == 0:               
            return False
    return True
if check_prime(int(input("Enter the Number--->"))):
    print(f"number is prime number.")
else:
    print(f"number is not prime number.")
    

Enter the Number---> 5


number is prime number.


In [1]:
# 30
start = int(input("enter starting range: "))
end = int(input("enter ending range: "))

print("prime number is:")
for i in range(start,end+1):
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i)


enter starting range:  2
enter ending range:  10


prime number is:
2
3
5
7


In [27]:
#31.Write a function that returns 
# both the minimum and maximum values in a list.

def min_max(lst):
    return min(lst),max(lst)

#list1 = [int(i) for i in input("Enter Number:").split()]
minimum, maximum = min_max([int(i) for i in input("Enter Number:").split()])
print("The minimum value of list is: ",minimum)
print("The maximum value of list is: ",maximum)

Enter Number: 5 6 55 0 256


The minimum value of list is:  0
The maximum value of list is:  256


In [28]:
# 32.Write a function that calculates the power of a number
# given a base and an exponent.

def power(base, exponent):
    return base ** exponent

print("The power of a number is ---> ",power(int(input("Enter Base: ")), int(input("Enter Exponent: "))))

Enter Base:  5
Enter Exponent:  3


The power of a number is --->  125


In [7]:
# 33. Write a function that displays personal information of the students. Use the concepts of default arguments and keyword arguments.

def info(enroll= 1, name='Dhruvi', course='MSC IT(DS)'):
    print("The Enrollment Number of student is:-", enroll)
    print("The Name of student is:-", name)
    print("The Course of student is:-", course)
print("KEYWORD ARGUMENTS:")
info(enroll = 3, name = 'niravi', course = 'MSC IT')
print("\nDEFUALT ARGUMENTS:")
info()

KEYWORD ARGUMENTS:
The Enrollment Number of student is:- 3
The Name of student is:- niravi
The Course of student is:- MSC IT

DEFUALT ARGUMENTS:
The Enrollment Number of student is:- 1
The Name of student is:- Dhruvi
The Course of student is:- MSC IT(DS)


In [60]:
# 34. Write a function that calculates the sum of an arbitrary number of numbers passed to the function.

def sum_of_arbitrary(*args):
    return sum(args)

print("The sum of numbers is: ",sum_of_arbitrary(*[int(i) for i in input("Enter Numbers:").split()]))

Enter Numbers: 1 2 3 4 5


The sum of numbers is:  15


In [68]:
# 35. Write a function that demonstrates the concepts of arbitrary keyword arguments (**kwargs).

def keyword_argument(**kwargs):
    #print("\nKEY-VALUE PAIR:")
    for key, value in kwargs.items():
        print(f'{key} : {value}')

# Taking user input for key-value pairs
# print("Enter key-value pairs (e.g., name=John age=30), separated by spaces:")
# Splitting input and converting it into a dictionary

# Calling the function with the dictionary unpacked as keyword arguments
keyword_argument(**dict(pair.split('=') for pair in input("Enter Arguments:\n").split()))

Enter Arguments:
 name=nirv num=3


name : nirv
num : 3


In [2]:
# 36. Write a recursive function that calculates the sum of all integers from 1 to n.

def recursive_func(n):
    if n == 1:
        return 1
    else:
        return n + recursive_func(n-1)
print(f"Sum from 1 to given number:", recursive_func(int(input("Enter the number: "))))

Enter the number:  5


Sum from 1 to given number: 15


In [7]:
# 37. Write a recursive function that finds the factorial value of a passed number to the function.

def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)

a = int(input("Enter the number: "))
print(f"Factorial number of {a}:", fact(a)) 

Enter the number:  5


Factorial number of 5: 120


In [3]:
# 38.Write a Python script to filter odd and even numbers from a list using lambda functions along with the filter() function.

l = [int(i) for i in input("Enter elements: ").split()]

odd_num = list(filter(lambda x : x % 2 != 0, l))
even_num = list(filter(lambda x : x % 2 == 0, l))


print(odd_num)
print(even_num)

Enter elements:  1 2 3 4 5 6


[1, 3, 5]
[2, 4, 6]


In [14]:
# 39. Write a Python script to demonstrate the concept of Function Decorators.

def my_decorator(func):
    def inner():
        print("Have a niced day !!")
        func()
        print("Good Bye !!")
    return inner

@my_decorator
def say_hello():
    print("Hy, Everyone !!!!")
    
say_hello()

Have a niced day !!
Hy, Everyone !!!!
Good Bye !!


In [1]:
# 40. Write a Python script to print 1 to 10 numbers using the concept of generators.

def my_generator(n):
    count = 1
    while count <= n:
        yield count
        count += 1
        
counter = my_generator(10)
for i in counter:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [5]:
# 41. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

import numpy as np

a = np.arange(100, 200, 10)
sampleArray = a.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [10]:
# 42. Create a 5 X 4 integer array using a random integer function and return array of odd rows and even columns.

import numpy as np

a = np.random.randint(0, 50, size = (5, 4))
print("Original Array:\n", a)

print("Array of odd rows and even columns:\n", a[::2, 1::2])

Original Array:
 [[13  9 26 29]
 [43 18 14  1]
 [14 19 39 49]
 [28 23 17 43]
 [41  3 48  6]]
Array of odd rows and even columns:
 [[ 9 29]
 [19 49]
 [ 3  6]]


In [4]:
# 43. Delete the second column from a given 3 X 3 array and insert the new column in its place.
import numpy as np

a = np.array([[1, 2, 3], [4 , 5, 6], [7 , 8, 9]])
print("Original Array:\n",a)

deleted_column_array = np.delete(a, 1, axis = 1)
print("Delete the second column from a given array:\n", deleted_column_array)

b = np.array([10, 11, 12])
insert_new_column_at_deleted_column = np.insert(deleted_column_array, 1, b, axis = 1)
print("insert the new column in its place:\n", insert_new_column_at_deleted_column)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Delete the second column from a given array:
 [[1 3]
 [4 6]
 [7 9]]
insert the new column in its place:
 [[ 1 10  3]
 [ 4 11  6]
 [ 7 12  9]]


In [9]:
# 44. Print max from axis 0 and min from axis 1 from the given 2-D array.
import numpy as np
print("Original Array:")
a = np.array([[1, 2, 3], [4 , 5, 6]])
print(a)

print("Max value from axis 0: ", np.max(a, axis = 0))
print("Min value from axis 1: ", np.min(a, axis = 1))

Original Array:
[[1 2 3]
 [4 5 6]]
Max value from axis 0:  [4 5 6]
Min value from axis 1:  [1 4]


In [8]:
# 45. Sort the 3 X 3 NumPy array by the second row using the function argsort() and display a new sorted array.
import numpy as np

a = np.array([[1, 2, 3], [6, 4, 5], [7 , 8, 9]])
print("Original Array:\n",a)

Second_row = a[1]
i = np.argsort(Second_row)
print("\nFirstly, the elements sorted and then it gives the old indices of elements", i)

print("\nNew sorted Array:")
new_arr = a[i]
print(new_arr)

Original Array:
 [[1 2 3]
 [6 4 5]
 [7 8 9]]

Firstly, the elements sorted and then it gives the old indices of elements [1 2 0]

New sorted Array:
[[6 4 5]
 [7 8 9]
 [1 2 3]]


In [11]:
# 46. Sort the 3 X 3 NumPy array by the second column using the function argsort() and display a new sorted array.

import numpy as np

a = np.array([[4,5,6],[1,2,3],[7,8,9]])
print("Original Array:\n",a)

Second_column = a[:,1]
i = np.argsort(Second_column)
print("\nIt gives the indices of second column", i)
print("\nNew sorted Array:")

new_arr = a[:, i]
print(new_arr)

Original Array:
 [[4 5 6]
 [1 2 3]
 [7 8 9]]

It gives the indices of second column [1 0 2]

New sorted Array:
[[5 4 6]
 [2 1 3]
 [8 7 9]]


In [13]:
# 47. Create a 5X2 integer array from a range between 1 to 100 such that the difference between each element is 10 
# and save it to a text file using a comma delimiter and then display the saved array back into the program.

import numpy as np

a = np.arange(1, 100, 10)
new_arr = a.reshape(5,2)
print("Orginal Array:\n",new_arr)

np.savetxt('MSC PRACTICAL.txt', new_arr, delimiter = ',')

load_txt = np.loadtxt('MSC PRACTICAL.txt', delimiter = ',')
print("Loaded Array from saved file:\n",load_txt)

Orginal Array:
 [[ 1 11]
 [21 31]
 [41 51]
 [61 71]
 [81 91]]
Loaded Array from saved file:
 [[ 1. 11.]
 [21. 31.]
 [41. 51.]
 [61. 71.]
 [81. 91.]]


In [14]:
# 48. Generate a 4x4 array of random integers between 1 and 50.
import numpy as np

a = np.random.randint(1, 50, size=(4,4))
print(a)

[[25 43 30 41]
 [23  4  3 14]
 [ 5  9 14 33]
 [14 38 37 14]]


In [2]:
# 49. Create the following csv file for employee data. Perform the following action using this employee csv file for pandas in python.

import pandas as pd

# 1.  Load the CSV file into a Pandas DataFrame and display the first 5 rows and last five rows.
df = pd.read_csv('employee_data.csv')
print("[1] First 5 rows:\n", df.head(5))
print("\nLast 5 rows:\n", df.tail(5))

# 2.  Select all employees who are older than 30 years.
older_than_30 = df['Age']>30
print("\n[2] Employees who are older than 30:\n ", df[older_than_30])

# 3.  Find the average salary and bonus for all employees.
avg_sal, avg_bonus = df['salary'].mean(), df['bonus'].mean()
print("\n[3] Average Salary:",avg_sal)
print("Average Bonus:",avg_bonus)

# 4.  Add a new column total_income which is the sum of salary and bonus for each employee.
df['Total_Income'] = df['salary'] + df['bonus']
print("\n[4] New DataFrame:\n", df)

# 5.  Group the employees by city and calculate the average salary and bonus for each city.
grouped_data = df.groupby('city').agg({'salary': ['mean'], 'bonus':['mean']})
print("\n[5] Group by city:\n", grouped_data)

# 6.  Sort the employees by salary in descending order.
sorted_data = df.sort_values('salary', ascending= False)
print("\n[6] Sorted Data:\n", sorted_data)

# 7.  Filter out employees where the bonus is greater than the salary.
bonus_salary = df['bonus'] > df['salary']
print("\n[7] The Data Where Bonus is greater than Salary:\n",df[bonus_salary])

# 8.  Check if there are any missing values in the DataFrame.
missing_value = df[df.isnull().any(axis=1)]
print("\n[8] Display missing Values if presented:\n",missing_value)

# 9.  Save all employees with a salary greater than 60,000 to a new CSV file.
new_employee_data = df['salary'] > 60000
print("\n[9] The below data is stored as new_employee_data file: \n", df[new_employee_data])
df[new_employee_data].to_csv('new_employee_data')

# 10. Increase the salary of all employees from 'Patan' by 10%.'''
dd =  df[df['city'] == 'Patan']
dd['salary'] = dd['salary'] + (dd['salary']*0.1)
print("\n[10] all employees of Patan with increasing 10% salary:\n", dd)

# 10. Increase the salary of all employees from 'Patan' by 10%.'''
df.loc[df['city'] == 'Patan', 'salary'] += df['salary'] * 0.1
print("\n\n[10] Whole table after increasing 10% salary of Patan Employee :\n", df)

[1] First 5 rows:
    eno   ename     city  Age  salary  bonus
0  101  Khyati    Patan   29   70000   5000
1  102    Diya  Mehsana   34   80000   7000
2  103    Raag    Unjha   40   65000   4000
3  104    Ansh  Chansma   25   55000   3000
4  105    Anvi      NaN   28   72000   4500

Last 5 rows:
    eno   ename     city  Age  salary  bonus
5  106   Nirvi  Mehsana   32   40000   4000
6  107    Juli    Unjha   45   25000   2000
7  108   Vinay  Chansma   54   35000   3000
8  109   Viswa  Mehsana   33   22000   2200
9  110  Bhoomi    Patan   29    1500   1550

[2] Employees who are older than 30:
     eno  ename     city  Age  salary  bonus
1  102   Diya  Mehsana   34   80000   7000
2  103   Raag    Unjha   40   65000   4000
5  106  Nirvi  Mehsana   32   40000   4000
6  107   Juli    Unjha   45   25000   2000
7  108  Vinay  Chansma   54   35000   3000
8  109  Viswa  Mehsana   33   22000   2200

[3] Average Salary: 46550.0
Average Bonus: 3625.0

[4] New DataFrame:
    eno   ename     city  

C:\Users\dhruv\AppData\Local\Temp\ipykernel_4944\1116461908.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['salary'] = dd['salary'] + (dd['salary']*0.1)
